# site name
prefixName: Ar-Sr-Na
siteName: 博客站
# favicon and site master avatar
favicon: https://res.arsrna.cn/icon2.jpg
avatar: https://res.arsrna.cn/icon2.jpg
url: https://www.arsrna.ltd
description: 女装只有cos90°次和tan90°次
cdn: 
pjax: 1
# 1开启
mathjax: 0

notice: 本站地址将于6月29从https://www.arsrna.cn迁移至https://b.arsrna.cn，请及时更换链接
lazyloadImg: https://res.arsrna.cn/slsblog/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  回到主站: { path: https://www.arsrna.cn/, fa: fa-archive faa-shake }
  友人帐: { path: /links, fa: fa-link faa-shake }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }
  政策: { path: https://www.arsrna.cn/policy/, fa: fa-leaf faa-wrench }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://www.arsrna.cn/hdpic.jpg
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash: 
  - {url: https://www.arsrna.cn/app/render/, title: 新应用, desc: ArSrNa 集群调度渲染助手, img: https://res.arsrna.cn/arsrna.cn/cr/workspace.png?imageMogr2/format/webp}
  - {url: https://www.arsrna.cn/#Dynamics, title: 云计算动态, desc: 主站内容发布, img: https://res.arsrna.cn/arsrna.cn/VOD.png_copwh}
  - {url: https://www.arsrna.cn, title: 主站, desc: 主站, img: https://www.arsrna.cn/hdpic.jpg}



# your site build time or founded date
siteBuildingTime: 12/12/2018

#social  url, img PC端配置
social:
  github: {url: https://github.com/ArSrNa, img: https://res.arsrna.cn/slsblog/github.png}
  zhihu: {url: https://www.zhihu.com/people/arsrna-87, img: https://res.arsrna.cn/slsblog/zhihu.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/Ar-Sr-Na, fa: fa-github, color: 333}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2459405337&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: 
  alipay: 
  wechat: https://res.arsrna.cn/sponsor/wechat.JPG?imageMogr2/format/webp
  wechatSQ: https://res.arsrna.cn/sponsor/alipay.JPG?imageMogr2/format/webp


# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://arsrnasitefr-1257609559.cos.ap-guangzhou.myqcloud.com
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: /videos/mmd%E8%83%8C%E6%99%AFweb_x264.mp4
  
aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: bYBEppifUgTsjjChokFXJefz-gzGzoHsz
v_appKey: 2eq935REyPu1yFkOS5UzRHNJ

